[package]
name = "xml-rs"
version = "0.8.0"
authors = ["Vladimir Matveev <vladimir.matweev@gmail.com>"]
license = "MIT"
description = "An XML library in pure Rust"
repository = "https://github.com/netvl/xml-rs"
documentation = "http://netvl.github.io/xml-rs/"
readme = "Readme.md"
keywords = ["xml", "parsing", "parser"]

[lib]
name = "xml"
path = "src/lib.rs"

[[bin]]
name = "xml-analyze"
path = "src/bin/analyze.rs"

[[bin]]
name = "xml-debug"
path = "src/bin/debug.rs"

[[bench]]
name = "decoding"
harness = false

[features]
default = ["encodings"]
encodings = ["encoding_rs"]

[dependencies]
encoding_rs = { version = "0.7", optional = true }
failure = "0.1"

[dev-dependencies]
quickcheck = "0.6"
criterion = "0.2"
rand = "0.4"
encoding = "0.2"

