[package]
name = "xml-rs"
version = "0.1.7"
authors = ["Vladimir Matveev <vladimir.matweev@gmail.com>"]
license = "MIT"
description = "An XML library in pure Rust"
repository = "https://github.com/netvl/xml-rs"

[lib]
name = "xml"
path = "src/lib.rs"
