[package]
name = "xml-rs"
version = "0.8.0"
authors = ["Vladimir Matveev <vladimir.matweev@gmail.com>"]
license = "MIT"
description = "An XML library in pure Rust"
repository = "https://github.com/netvl/xml-rs"
documentation = "http://netvl.github.io/xml-rs/"
readme = "Readme.md"
keywords = ["xml", "parsing", "parser"]
edition = "2018"

[lib]
name = "xml"
path = "src/lib.rs"

[[bin]]
name = "xml-analyze"
path = "src/bin/analyze.rs"

[[bin]]
name = "xml-debug"
path = "src/bin/debug.rs"

[[bench]]
name = "decoding"
harness = false

[dependencies]
encoding_rs = "0.8.17"
nom = "5.1.0"
thiserror = "1.0.9"
derive_more = "0.99.2"
arraydeque = "0.4.5"
aho-corasick = "0.7.6"

[dev-dependencies]
quickcheck = "0.8.5"
criterion = "0.2.11"
rand = "0.7.0"
encoding = "0.2.33"
itertools = "0.8.2"
regex = "1.3.3"

